site_name: Django Vector Database
site_url: https://github.com/pkavumba/django-vectordb
site_description: Django Vector Database - Adds fast vector search app any Django project

repo_url: https://github.com/pkavumba/django-vectordb

markdown_extensions:
  - toc:
      anchorlink: True

nav:
  - Home: "index.md"
  - Tutorial:
      - "Quickstart": "tutorial/quickstart.md"
      - "1 - Project Setup": "tutorial/1-project-setup.md"
      - "2 - Adding Vector Search": "tutorial/2-adding-vector-search.md"
      - "3 - Manually Updating Vector Database": "tutorial/3-manually-updating-vector-database.md"
      - "4 - Manually Updating Vector Database": "tutorial/4-manually-updating-vector-database.md"
      - "5 - Automatically Syncing Our Models to Vector Database": "tutorial/5-automatic-syncing.md"
      - "6 - Vector Searching": "tutorial/6-vector-search.md"
      - "7 - Adding a Vector Search Endpoint": "tutorial/7-adding-api-endpoint.md"
