site_name: Django Vector Database
site_url: https://github.com/pkavumba/django-vectordb
site_description: Django Vector Database - Adds fast vector search app any Django project

repo_url: https://github.com/pkavumba/django-vectordb

theme:
  name: material
  features:
    - content.code.copy
    - content.code.select

markdown_extensions:
  - toc:
      anchorlink: True
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition

nav:
  - Home: "index.md"
  - Tutorial:
      - "Quickstart": "tutorial/quickstart.md"
      - "1 - Project Setup": "tutorial/1-project-setup.md"
      - "2 - Adding Vector Search": "tutorial/2-adding-vector-search.md"
      - "3 - Automatically Updating Django Vector Database": "tutorial/3-automatically-updating-vector-database.md"
      - "4 - Manually Updating Django Vector Database": "tutorial/4-manually-updating-vector-database.md"
      - "5 - Vector Searching": "tutorial/5-vector-search.md"
      - "6 - Adding a Vector Search Endpoint": "tutorial/6-adding-api-endpoint.md"
